### ISSUE TITLE
Package names with comparators should be enclosed in double quotes for `pip install`

### ISSUE THREAD

**Issue by mpitblado** [Gene-Weaver/LeafMachine2#14]
While installing some of the packages, I encountered errors for versioned packages using `>=` or `<=` on zsh. This can be fixed by enclosing the packages and their version requirements in quotations.

From [the python documentation](https://docs.python.org/3/installing/index.html#basic-usage)

> It’s also possible to specify an exact or minimum version directly on the command line. When using comparator operators such as >, < or some other special character which get interpreted by shell, the package name and the version should be enclosed within double quotes:

```shell
python -m pip install SomePackage==1.0.4    # specific version
python -m pip install "SomePackage>=1.0.4"  # minimum version
```

**Comment by Gene-Weaver** [comment]
Thanks, I changed the readme for the packages that are not in the requirements.txt
